splashRadar._JSINIT=!0;splashRadar._JSINITTime=(new Date).getTime();splashRadar._JSLOADTime=(new Date).getTime()-splashRadar._JSLOADTime;splashRadar("JSLoad",1);splashRadar("JSInit");
(function(a){function b(b,d){var c=a.m$portal.cookie,e,g,u=RegExp("(^|\\|)("+b+"=)(.*?)(\\||$)");if(b)return e=c("s")||"",g=(e.match(u)||[])[3],void 0!==d?c("s",g||null===d?e.replace(u,null===d?function(b,a,d,c,e,i,g){return 0===g.indexOf(b)?"":e}:"$1$2"+d+"$4"):(e?e+"|":"")+b+"="+d,{domain:".mail.ru",expires:365,path:"/"}):d=g,d}var c={splash:"s",news:"n",afisha:"a",auto:"av",lady:"l",horo:"h",pogoda:"p",mail:"m",promail:"pm",blogs:"b",foto:"f",video:"v",my:"my",agent:"ag",torg:"t",love:"lv",game:"g",
"hi-tech":"ht",maps:"map"},d,e=a.m$portal;e||(e=a.m$portal={});e.S_Cookie=function(a){d||(a=c[a],d=new function(){function d(){throw Error("project must be set");}function c(e){a||d();return b(a+"_"+e)}this.getLocal=c;this.setLocal=function(e,g){a||d();if(void 0==g)throw Error("need value");b(a+"_"+e,g);return c(e)};this.removeLocal=function(e){a||d();var g=c(e);b(a+"_"+e,null);return g};this.getGlobal=function(a){return b(a)};this.setGlobal=function(a,d){if(void 0==d)throw Error("need value");b(a,
d);return b(a)};this.removeGlobal=function(a){var d=b(a);b(a,null);return d}});return d}})(window);Splash.getUniqueId=function(){var a=0;return function(){return a++}}();
extend(mr,{getLf1Url:function(a,b){var b=(b||location.href).replace(/https?:\/\/(\S+\.)*?mail.ru/i,"//lf1.mail.ru"),c=-1===b.indexOf("?")?"?":"&";if(a)for(var d in a)a.hasOwnProperty(d)&&(b+=c+d+"="+encodeURIComponent(a[d]),c="&");return b},tag:function(a,b,c){if(c&&document.querySelectorAll)return(b||document).querySelectorAll(a+"."+c);a=(b||document).getElementsByTagName(a);if(c){for(var b=[],d=0;d<a.length;d++){var e=a[d];mr.hasClass(e,c)&&b.push(e)}return b}return a},toggleClass:function(a,b,
c,d){!1===d||void 0===d&&mr.hasClass(a,b)?(mr.removeClass(a,b),c&&mr.addClass(a,c)):(mr.addClass(a,b),c&&mr.removeClass(a,c))},hasParent:function(a,b){var c;c=mr.isNode(b)?function(a,b){return a==b}:function(a,b){return mr.hasClass(a,b)};for(var d=a.parentNode;d;){if(c(d,b))return d;d=d.parentNode}return!1},isNode:function(a){return a&&1==a.nodeType},preventDefault:function(a){a&&a.preventDefault?a.preventDefault():window.event.returnValue=!1},s_cookie:m$portal.S_Cookie("splash"),data:function(a,
b,c){if(!a)return null;if(void 0===c)return a.getAttribute("data-"+b);a.setAttribute("data-"+b,c)},proxy:function(a,b){return function(){return a.apply(b,arguments)}},position:function(a){if(a.getBoundingClientRect){var a=a.getBoundingClientRect(),b=document.body,c=document.documentElement;return{left:a.left+(window.pageXOffset||c.scrollLeft||b.scrollLeft)-(c.clientLeft||b.clientLeft||0),top:a.top+(window.pageYOffset||c.scrollTop||b.scrollTop)-(c.clientTop||b.clientTop||0)}}b=parseFloat(a.offsetTop);
for(c=parseFloat(a.offsetLeft);a=a.offsetParent;)b+=parseFloat(a.offsetTop),c+=parseFloat(a.offsetLeft);return{left:c,top:b}},getJson:function(a,b,c,d){new Ajax(a,{json:!0,params:b,callback:c,error:d})},_jsonpId:0,JSONP:function(a){var b=a.url,c=a.params,d=a.getName||"callback",e=a.callback,i=a.error,a=a.timeout,f=document.createElement("script"),k="__jsonp_"+mr._jsonpId++;window[k]=function(a){clearTimeout(f._timeout);e(a)};a&&(f._timeout=setTimeout(function(){i()},a));c||(c={});c[d]=k;c.rnd=(new Date).getTime()+
Math.random();c=mr.formatQuery(c);f.src=b+(0<b.indexOf("?")?"&":"?")+c;document.getElementsByTagName("head")[0].appendChild(f)},formatQuery:function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")},parseJson:function(a){if("string"!==typeof a||!a)return null;try{return window.JSON&&window.JSON.parse?window.JSON.parse(a):(new Function("return "+a))()}catch(b){return window.logError&&logError(b,"parseJson"),null}},plural:function(a){return 1==
a%10&&11!=a%100?0:2<=a%10&&4>=a%10&&(10>a%100||20<=a%100)?1:2},placeSlot:function(a){var b=mr.id("slot_"+a),a=mr.id("placeholder_"+a);b&&a&&(a.innerHTML=b.innerHTML)},placeSlots:function(){for(var a=0;a<arguments.length;a++)mr.placeSlot(arguments[a])},extendClass:function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a}});
function Ajax(a,b){var c=this.getTransport();if(c){var d=b.method||"get",e=b.json||!1,i=b.params||{},f=b.callback||function(){},k=b.error||function(){};"get"==d&&b.params&&(a+=(-1!=a.indexOf("?")?"&":"?")+mr.formatQuery(i));c.onreadystatechange=function(){var a;if(4===c.readyState){if(200===c.status)if(e){var b;try{b=mr.parseJson(c.responseText)}catch(d){window.logError&&logError(d,"readyState"),a=d,window.console&&window.console.error&&console.error(d)}a||f(b)}else f(c.responseText);if(200!==c.status||
a)k(a instanceof Error&&a||Error("request error"))}};c.open(d,a,!0);c.send("get"==d?null:mr.formatQuery(i))}}Ajax.prototype={getTransport:window.ActiveXObject&&!window.XMLHttpRequest?function(){try{return new window.ActiveXObject("Microsoft.XMLHTTP")}catch(a){window.logError&&logError(a,"getTransport_IE")}}:function(){try{return new window.XMLHttpRequest}catch(a){window.logError&&logError(a,"getTransport_XHR")}}};
(function(){function a(a){this._context=a||this;this._mixedIn=[]}function b(a,b,e){this.eventName=a;this.target=b;this.data=e}a.prototype.emit=function(a,d){var e;if(!this._events||!this._events[a]||!(e=this._events[a]))return!1;for(var i=0,f=e.length;i<f;i++){var k=e[i];"function"===typeof k&&k.apply(this._context,[new b(a,this._context,d)])}return!0};a.prototype.addListener=function(a,b){if("function"!==typeof b)throw Error("invalid argument");this._events||(this._events={});this._events[a]||(this._events[a]=
[]);this._events[a].push(b);return this};a.prototype.on=a.prototype.addListener;a.prototype.once=function(a,b){function e(){this.removeListener(a,e);b.apply(this._context,arguments)}if("function"!==typeof b)throw Error("invalid argument");this.on(a,e);return this};a.prototype.removeListener=function(a,b){if("function"!==typeof b)throw Error("invalid argument");if(!this._events[a])return this;var e=this._events[a],i=e.indexOf(b);if(0>i)return this;e.splice(i,1);0===e.length&&delete this._events[a];
return this};a.prototype.mixin=function(a){a.bind=this.bind.bind(this);a.unbind=this.unbind.bind(this);a.dispatch=this.dispatch.bind(this);this._mixedIn.push(a)};a.prototype.bind=function(a,b){this.on(a,b);return this};a.prototype.unbind=function(a,b){this.removeListener(a,b)};a.prototype.dispatch=function(a,b){this.emit.apply(this,arguments)};a.prototype.destroy=function(){for(var a=0,b=this._mixedIn.length;a<b;a++){var e=this._mixedIn[a];e.bind=e.unbind=e.dispatch=void 0}this._mixedIn=this._events=
this._context=void 0};Splash.EventEmitter=a})();
(function(){function a(a,b,c){this._elem=a;this._name=b;this._fn=c;this._attached=!1;this._handler=mr.proxy(this._fn,this)}var b=0,c={};a.addListener=function(d,e,i){if(Array.prototype.isArray(d)){for(var f=0,k=d.length;f<k;f++)d[f]&&a.addListener(d[f],e,i);return this}e=Array.prototype.isArray(e)?e:[e];f=!1;i.uuid&&(f=!0);var n=i.uuid||b;i.uuid=n;n=c[n]=function(a){var a=Event._fix(a||window.event),b=i.call(d,a);!1===b&&(a.preventDefault(),a.stopPropagation());return b};f||b++;f=0;for(k=e.length;f<
k;f++)document.addEventListener?d.addEventListener(e[f],n,!1):d.attachEvent("on"+e[f],n);return this};a.on=a.addListener;a.removeListener=function(b,e,i){if(Array.prototype.isArray(b)){for(var f=0,k=b.length;f<k;f++)b[f]&&a.removeListener(b[f],e,i);return this}e=Array.prototype.isArray(e)?e:[e];f=0;for(k=e.length;f<k;f++)document.removeEventListener?b.removeEventListener(e[f],c[i.uuid],!1):b.detachEvent("on"+e[f],c[i.uuid]);return this};a.once=function(b,e,c){function f(k){c.call(this,k);a.removeListener(b,
e,f)}this.on(b,e,f);return this};a.prototype={attach:function(){this._attached||(this._attached=!0,this._attach())},detach:function(){this._attached&&(this._detach(),this._attached=!1)},_attach:function(){a.on(this._elem,this._name,this._handler)},_detach:function(){a.removeListener(this._elem,this._name,this._handler)},destroy:function(){this.detach();this._elem=this._name=this._fn=this._handler=null}};Event={_fixHooks:{key:{props:["charCode","keyCode"],fix:function(a,b){a.which||(a.which=b.charCode?
b.charCode:b.keyCode);return a}},mouse:{props:"clientX clientY offsetX offsetY pageX pageY screenX screenY".split(" "),fix:function(a,b){var c,f,k=b.button,n=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||document,f=c.documentElement,c=c.body,a.pageX=b.clientX+(f&&f.scrollLeft||c&&c.scrollLeft||0)-(f&&f.clientLeft||c&&c.clientLeft||0),a.pageY=b.clientY+(f&&f.scrollTop||c&&c.scrollTop||0)-(f&&f.clientTop||c&&c.clientTop||0));!a.relatedTarget&&n&&(a.relatedTarget=n===a.target?
b.toElement:n);!a.which&&void 0!==k&&(a.which=k&1?1:k&2?3:k&4?2:0);return a}},touch:{props:["touches","targetTouches","changedTouches"],fix:function(a){return a}}},_props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase shiftKey target timeStamp which".split(" "),_fix:function(a){var b={preventDefault:function(){a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}},c=a.type,f=/^(key|mouse|touch)/.exec(c);
f&&-1!==["key","mouse","touch"].indexOf(f[1])&&(c=f[1]);"click"===c&&(c="mouse");for(var c=this._fixHooks[c]||{},f=c.props?this._props.concat(c.props):this._props,k=f.length;k;){var n=f[--k];b[n]=a[n]}b.target&&3===b.target.nodeType&&(b.target=b.target.parentNode);b.target||(b.target=a.srcElement||document);c.fix&&c.fix(b,a);b.originalEvent=a;b.type=a.type;b.timeStamp=a&&a.timeStamp||(new Date).valueOf();return b}};Splash.DOMEvent=a})();
(function(a,b){function c(a,c,i){this.content=a;this.tipSide=i||"bottom";this.listenTo=c;this.node=b.createElement("div");this.node.className="hint";-1!==navigator.userAgent.indexOf("MSIE 6")&&(this.nodeIE=b.createElement("iframe"),this.nodeIE.className="hint hint_iframe");this._prepareHTML();this._prepareEvents();this.enable()}c.prototype=new Splash.EventEmitter;mr.extend(c.prototype,{isVisible:function(){return this._visible},show:function(a){if(!(a&&!this._visible||!a&&this._visible)){this._inBody||
(this.nodeIE&&b.body.appendChild(this.nodeIE),b.body.appendChild(this.node),this._inBody=!0);a||this.emit("show");this.node.style.visibility="hidden";this.node.style.display="block";var a=mr.position(this.listenTo),c=this.node.offsetHeight,i=this.node.offsetWidth;this.node.style.left=a.left+this.listenTo.offsetWidth/2-22+"px";this.node.style.top=a.top-c-6+"px";this.nodeIE&&(this.nodeIE.style.width=i,this.nodeIE.style.height=c,this.nodeIE.style.left=this.node.style.left,this.nodeIE.style.top=this.node.style.top,
this.nodeIE.style.display=this.node.style.display,this.nodeIE.style.visibility="visible");this.node.style.visibility="visible";this._visible=!0}},hide:function(){this.node.style.display="none";this.nodeIE&&(this.nodeIE.style.display=this.node.style.display);this._visible=!1},_prepareHTML:function(){var a='<i class="hint__tip hint__tip_'+this.tipSide+'">'+(-1!==navigator.userAgent.indexOf("MSIE 6")?'<i class="hint__tip_ie"></i>':"")+'</i><div class="hint__content">'+this.content;this.node.innerHTML=
a;this.show(!0)},setContent:function(a){this.content=a;this._prepareHTML()},_prepareEvents:function(){var a;this._showEvent=new Splash.DOMEvent(this.listenTo,"mouseover",mr.proxy(function(){clearTimeout(a);a=setTimeout(mr.proxy(function(){this.show()},this),100)},this));var b=mr.proxy(function(){clearTimeout(a);a=setTimeout(mr.proxy(function(){this.hide()},this),400)},this);this._hideEvent=new Splash.DOMEvent(this.listenTo,"mouseout",b);mr.bind(this.node,"mouseover",function(){clearTimeout(a)});mr.bind(this.node,
"mouseout",b)},enable:function(){this._showEvent.attach();this._hideEvent.attach()},disable:function(){this._showEvent.detach();this._hideEvent.detach()},destroy:function(){this.node.parentNode.removeChild(this.node);this._showEvent.destroy();this._hideEvent.destroy();this._events.destroy();this._events=this._hideEvent=this._showEvent=this.content=this.tipSide=this.listenTo=this.node=null}});Splash.Hint=c})(window,document,void 0);
(function(){function a(a,c){this.container=a;this.options=c;this.mask=mr.id(c.mask.maskId);this.contentContainer=mr.id(c.content.containerId);this.more=mr.id(c.tabs.moreId);this.moreContainer=mr.id(c.tabs.moreDropdownId);var d=this;this.__onClick=function(a){d._onClick(this,a)};for(var e=this.container.getElementsByTagName("td"),i=0,f=e.length;i<f;i++)this._initTab(e[i]);this._closeMore=this._closeMore.bind(this);Splash.DOMEvent.addListener(this.more,"click",this._openMore.bind(this))}a.prototype=
new Splash.EventEmitter;mr.extend(a.prototype,{_initTab:function(a){this.isActive(a)&&(this.activeTab=a);this._loadTabContent(a);this._initDouble(a);Splash.DOMEvent.addListener(a,"click",this.__onClick)},loaded:function(){this._waiting&&this._waiting();this.emit("loaded")},_initDouble:function(a){mr.hasClass(a,this.options.tabs.doubleTabClass)&&(a._double=document.createElement("div"),a._double.className=this.options.tabs.moreDropdownItemClass,a._double.innerHTML=a.innerHTML.replace(RegExp(this.options.tabs.tabLinkClass,
"g"),this.options.tabs.moreDropdownItemLinkClass),a._double.tab=a,Splash.DOMEvent.addListener(a._double,"click",this.__onClick),this.moreContainer.appendChild(a._double))},_openMore:function(a){!mr.hasParent(a.target,this.moreContainer)&&!mr.hasClass(this.more,this.options.tabs.moreOpenedClass)&&(mr.counter("clb818633"),mr.addClass(this.more,this.options.tabs.moreOpenedClass),setTimeout(function(){Splash.DOMEvent.addListener(document,"click",this._closeMore)}.bind(this),0))},_closeMore:function(){mr.removeClass(this.more,
this.options.tabs.moreOpenedClass);Splash.DOMEvent.removeListener(document,"click",this._closeMore)},_loadTabContent:function(a){if(a._content)return!0;var c=document.getElementById("slot_"+a.getAttribute("data-slot"));if(c){var d;mr.hasClass(c.parentNode,this.options.content.tabClass)?d=c.parentNode:(d=document.createElement("div"),d.className=this.options.content.tabClass,d.style.display="none",c.style.display="",this.contentContainer.appendChild(d),d.appendChild(c));a._content=d;return!0}return!1},
_onClick:function(a,c){a.tab&&(a=a.tab);this.isActive(a)||(c.preventDefault(),this.activateTab(a))},isActive:function(a){return mr.hasClass(a,this.options.tabs.tabActiveClass)},activateTab:function(a){this.activeTab&&this.deactivateTab(this.activeTab);var c=a.getAttribute("data-counters");c&&mr.counter(c);mr.addClass(a,this.options.tabs.tabActiveClass);this._loadTabContent(a)?(a._content.style.display="block",this._waiting=null,this.mask.style.display="none"):(this.mask.style.display="block",this._waiting=
function(){this._loadTabContent(a);a._content.style.display="block";this.mask.style.display="none"});a._double?(mr.addClass(a._double,this.options.tabs.moreDropdownItemSelectedClass),mr.addClass(this.more,this.options.tabs.moreSelectedClass)):mr.removeClass(this.more,this.options.tabs.moreSelectedClass);this.activeTab=a;this.emit("tab:activate",a)},deactivateTab:function(a){mr.removeClass(a,this.options.tabs.tabActiveClass);this._loadTabContent(a)&&(a._content.style.display="none");a._double&&mr.removeClass(a._double,
this.options.tabs.moreDropdownItemSelectedClass);this.activeTab=null}});Splash.News=a})();
(function(a,b,c){function d(a){var b=a.relatedTarget,p=!1,c=a.type;a.type=la[c];if(b!==this&&(b&&(p=l.contains(this,b)),!p))b=l.mkarr(arguments),m.fire(this,b.shift(),b),a.type=c}function e(h){function A(a,h){return m.add(aa,a,h)}function c(a,h){a&&m.rm(aa,a,h)}function j(a,h){a&&m.fire(aa,a,h)}function f(){return{current:Q.curr,recent:Q.rcnt,previous:Q.prev,value:F,data:H,fullData:P,focused:L(J),method:ba,selected:L(W),result:V(W),itemData:N(W),hovered:L(M),items:l.mkarr(R)}}function d(){M=J=W=ba=
P=H=F=null}function g(a){J=null;S(a.currentTarget)}function i(){}function k(){}function u(){}function n(a){a[ha]();a[X]();a=L(a.currentTarget);-1!=a&&(ba="mouse",za(a))}function x(){if(/^(?:relative|absolute|fixed)$/i.test(l.css(G,"position"))){var h=ma({},w.getBoundingClientRect());h.left+=a.pageXOffset+(q.shiftX||0);h.top+=a.pageYOffset+w.offsetHeight+(q.shiftY||0);l.css(G,"left",h.left+"px");l.css(G,"top",h.top+"px")}}function z(a){a=a?"on":"off";l.attr(w,"autocomplete",a);l.attr(w,"autocapitalize",
a);l.attr(w,"autocorrect",a);ca&&(ia(ca),ca=null);l.hasFocus(w)&&(w.blur(),ca=Y(function(){(!b.activeElement||!/^(?:a|input|textarea|select|button|)$/i.test(b.activeElement.tagName)||l.hasFocus(w))&&w.focus();ca&&(ia(ca),ca=null)},25))}function D(){ia(na);na=null}function t(){na=Y(function(){Aa?t():(ia(na),na=null,T())},50)}function E(){Aa=!0}function s(){Aa=!1;m.fire(w,"focus")}function y(){ia(ua);ua=null}function v(a){var h=a.keyCode,b=a.shiftKey,A=a.ctrlKey;switch(!0){case !A&&!b&&(38==h||40==
h)&&!U():a[X]()}if(!ua)switch(ua=Y(y,q.keynavDelay),!0){case 13==h:if(!U()&&J&&(ba="keyboard",h=za(J,!0),!q.autoSubmit||!1===h))a[X]();break;case 27==h:U()||(T(),$(),Y($,15),a[X]());break;case !A&&!b&&38==h:U()||Z(-1);break;case !A&&!b&&39==h:!U()&&null!=P&&null!=H&&null!=F&&J&&V(J)!==F&&Ba(V(J));break;case !A&&!b&&40==h:U()?Ba():Z(1)}}function I(){y()}function L(a){var h;"number"===typeof a?h=a:a&&a.nodeType&&(h=l.indexOf(R,a));return"number"===typeof h&&!isNaN(h)?h:-1}function qa(a){var h;if("number"===
typeof a)h=R[a];else if(a&&a.nodeType&&~(a=l.indexOf(R,a)))h=R[a];return h||null}function N(a){a=L(a);return H&&null!=H[a]?H[a]:null}function S(a){var h=qa(a),b=q.hover;!M&&!h||M===h||(b&&("string"===typeof b?(M&&l.rmCls(M,b),h&&l.addCls(h,b)):K(b)&&(M&&(a=L(M),b(!1,M,N(a),a,F)),h&&(a=L(h),b(!0,h,N(a),a,F)))),M=h)}function ka(a){var a=L(a),h=qa(a),b=N(a);S(a);j(r.focus,[b,a,F]);J=h;if(q.preview){var h=L(a),A=N(h),h=null!=A?q.result(A,h,P,F):F;Q.setIgnore(h)}j(r.focusEnd,[b,a,F])}function Z(a){var h=
J||M,b=h?L(h):-1,h=R.length-1,a=b+a;-1>a?a=h:a>h&&(a=-1);ka(a)}function V(a){var a=L(a),h=N(a);return null!=h?q.result(h,a,P,F):null}function $(){Q.setIgnore(F);w.value=F}function za(h,A){h=L(h);W=-1==h?null:qa(h);ka(h);N(h);var c=q.select,p,d=!1;j(r.select,f());T();$();K(c)&&(p=c(f()));var g;if(g=!1!==p)g=L(h),(g=V(g))&&Q.setIgnore(g),g=da&&q.autoSubmit;if(g)if(A)d=!0;else{var e=!1;b.createEvent?(Ca(da,"submit",function(h){h=h||a.event;e=Ga(h);ea.preventDefault.call({origEvt:h})}),c=b.createEvent("HTMLEvents"),
c.initEvent("submit",!1,!0),da.dispatchEvent(c)):b.createEventObject&&(c=b.createEventObject(),e=!da.fireEvent("onsubmit",c));!1===e&&da.submit()}d?b[va]?Ca(da,"submit",Da):Ca(da,"submit",function(){Y(Da,50)}):Da();return p}function Da(){var a=q.unselect;K(a)&&a(f());j(r.selectEnd,f());W=ba=null}function Ba(a){null!=P&&null!=H&&null!=F&&(!a||a===F)?(Ea(),J&&ka(J)):a?Q.fireVal(a,!0):Q.fire(!0)}function U(){var a=!0,h=q.switcher,b=q.switchChecker;h?"string"===typeof h?a=!l.hasCls(G,q.switcher):K(h)&&
K(b)&&(a=!b()):a="none"===l.css(G,"display");return a}function Ea(){if(U()){j(r.open,[F]);var a=q.switcher;a?"string"===typeof a?l.addCls(G,a):K(a)&&a(!0,G):l.css(G,"display","block");q.correction&&x();j(r.openEnd,[F])}}function T(){if(!U()){j(r.close,[F]);var a=q.switcher;a?"string"===typeof a?l.rmCls(G,a):K(a)&&a(!1,G):l.css(G,"display","none");j(r.closeEnd,[F])}}function la(a){a.target!==w&&T()}function Fa(){x()}function ra(){oa&&(j(r.enable),m.add(b,"click",la),m.add(G,"click",fa),m.add(w,"focus",
D),m.add(w,"blur",t),m.add(G,"mousedown",E),m.add(G,"mouseup",s),m.add(w,O?"keypress":"keydown",v),m.add(w,"keyup",I),q.correction&&m.add(a,"resize",Fa),z(!1),Q.init(),oa=!1,j(r.enableEnd))}function sa(){oa||(j(r.disable),T(),Q.off(),Ha.abortAll(),z(!0),m.rm(b,"click",la),m.rm(G,"click",fa),m.rm(w,"focus",D),m.rm(w,"blur",t),m.rm(G,"mousedown",E),m.rm(G,"mouseup",s),m.rm(w,O?"keypress":"keydown",v),m.rm(w,"keyup",I),q.correction&&Fa&&m.rm(a,"resize",Fa),l.empty(wa),R.length=0,M=J=W=ba=null,oa=!0,
j(r.disableEnd))}function ya(a){try{console.log(a.type,arguments)}catch(h){}}function ta(a,h){var b=arguments.length;if(0==b)return q;if(1==b&&"object"!==typeof a)return l.walker(q,a);"object"!==typeof a&&(b={},b[a]=h,a=b);var j;j=a;if(null==j)j=null;else{var g={};(function Ia(a,h){a&&(l.isObj(a)?l.objEach(a,function(a,b){Ia(a,(h?h+".":"")+b)}):h&&(g[h]=a))})(j);j=g}(b=j)&&l.objEach(b,function(a,h){var b=l.walker(q,h,a);if(/(?:^on[A-Z])/.test(h.substr(0,3))&&K(a)){var j=h.charAt(2).toLowerCase()+
h.slice(3);if(j=e.evt[j])b&&c(j,b),A(j,a)}})}var aa=this,Q={run:!1,did:null,prev:null,rcnt:null,curr:null,ignr:null,init:function(){this.run||(this.curr=this.prev=w.value,this.on())},handler:function(a){var h=this.curr=w.value,b=this.prev;if(a||h!==b){!a&&null==this.ignr&&(this.rcnt=b);this.prev=h;if(a||null==this.ignr||this.ignr!==h){j(r.valueChange,[h,b,this.rcnt]);var a=""+h,b=a.length,A=!0;if(q.valMin&&b<q.valMin||q.valMax&&b>q.valMax)A=!1;b=q.valFilter;A&&b&&(A=b instanceof RegExp?b.test(a):
K(b)?b(a):b===a);A?(j(r.passFilter,[h]),Ha.send(h,function(a,h){if(h===w.value){var b=q.dataGet;F=h;H=(P=a)&&K(b)?b(P):P;b=!1;if(!P||!H||!H.length||q.min&&q.min>H.length)b=!0;if(b)j(r.rejectData,[a,h]),d(),T();else{j(r.acceptData,[a,h]);l.empty(wa);R.length=0;M=J=W=ba=null;j(r.render,[H,F]);for(var b=q.max?Math.min(H.length,q.max):H.length,A=0,c,p=K(q.item)?q.item:l.tmpl(q.item);A<b;A++){c=H[A];(c=p({itemData:c,fullData:P,index:A,value:F}))&&"string"===typeof c&&(c=l.cre(c));if(!c||!c.nodeType)break;
m.add(c,"click",n);m.add(c,"mouseenter",g);m.add(c,"mouseleave",i);m.add(c,"mousedown",k);m.add(c,"mouseup",u);R.push(c);wa.appendChild(c)}j(r.renderEnd,[R,H,F]);Ea()}}},function(a,h){h===w.value&&(d(),T())})):(j(r.failFilter,[h]),d(),T())}this.ignr=null}},fire:function(a){this.off();this.handler(a);this.on()},fireVal:function(a,h){this.off();w.value=a;this.handler(h);this.on()},on:function(){if(!this.run){var a=this;this.run=!0;this.did=B(function(){a.handler()},q.delay)}},off:function(){this.run&&
(this.run=!1,Ja(this.did),this.did=null)},setIgnore:function(a){w.value!==a&&(this.ignr=w.value=a)}},pa={c:{},i:0,set:function(a,h){j(r.setCache,[a,h]);q.cchLimit&&this.i+1>=q.cchLimit&&this.flush();this.c[a]=h;this.i++;j(r.setCacheEnd,[a,h,this.i])},get:function(a){j(r.getCache,[a]);var h=this.has(a)?this.c[a]:null;j(r.getCacheEnd,[a,h]);return h},has:function(a){return null!=this.c[a]&&C.call(this.c,a)},flush:function(){j(r.flushCache);var a=this.c,h;for(h in a)C.call(a,h)&&delete a[h];this.i=0;
j(r.flushCacheEnd)}},Ha={act:[],actVals:{},isAct:function(a){return!arguments.length?!!this.act.length:!!this.actVals[a]&&C.call(this.actVals,a)},add:function(a,h){var b=this.act;q.reqMax&&b.length&&b.length>=q.reqMax&&this.rm(b[0]);this.actVals[h]=a;return b.push(a)},rm:function(a){if(a){a.abort();var h=l.indexOf(this.act,a);~h&&this.act.splice(h,1);var b=this.actVals;for(h in b)if(b[h]===a){delete b[h];break}return this.act.length}},abortAll:function(){for(var a=this.act,h=this.actVals,b=a.length;b--;)a[b]&&
a[b].abort();a.length=0;for(b in h)delete h[b]},stack:function(){return l.mkarr(this.act)},send:function(a,h,b){if(!a)return!1;var A=this;if(q.cch&&pa.has(a))return h&&h(pa.get(a),a),!0;if(this.isAct(a))return j(r.blockRequest,["running",a]),!1;var c=q.url,p={query:a},c="object"===typeof c?l.url(l.objFormat(c,p)):l.format(c,ga(p)),g=Ka({timeout:q.reqTimeout,callbackParam:q.callbackParam,scriptCharset:q.scriptCharset,data:q.reqData,success:function(b){j(r.successRequest,[b,a]);j(r.completeRequest,
[b,a]);var c=q.dataFilter;K(c)&&(b=c(b,a));A.rm(g)||j(r.stopRequest,[a]);q.cch&&pa.set(a,b);h&&h(b,a)},error:function(h){j(r.errorRequest,[h,a]);j(r.completeRequest,[h,a]);A.rm(g)||j(r.stopRequest,[a]);b&&b(h,a)}});1==A.add(g,a)&&j(r.startRequest,[a]);j(r.sendRequest,[a]);g.send(c);return!0}},P=null,H=null,F=null,ca,na,ua,q=l.copy(e.opts);ta(h);var w=q.field&&xa(q.field),da=w&&w.form,G=xa(q.cont),wa=q.list&&G?xa(q.list,G):G,R=[],M,J,W,Aa,oa=!0,ba=null;if(!w||!G||!wa)throw"";q.debug&&l.objEach(r,function(a){A(a,
ya)});ma(this,{show:Ba,focus:ka,moveFocus:Z,select:za,open:Ea,close:T,isClosed:U,enable:ra,disable:sa,isDisabled:function(){return oa},destroy:function(){j(r.destroy);sa();q.cch&&pa.flush();c();j(r.destroyEnd);delete e.instances[aa.guid]},on:A,off:c,getState:f,opts:ta,flushCache:function(){pa.flush()}});aa.guid=ja++;e.instances[aa.guid]=aa;q.enabled&&ra()}var i,f=b,k=function(a){var b,p;if(a&&(p=a.length)!==c)try{b=Array.prototype.slice.call(a)}catch(j){for(b=Array(p);p--;)b[p]=a[p]}return b||[]},
n=function(a,b){var p=[],b=b?n(b)[0]:f;if(!a)return p;if(a.nodeType||"object"===typeof a&&"setTimeout"in a)return[a];if("object"===typeof a&&("[object Array]"===Object.prototype.toString.call(a)||a.length!==c))return k(a);if(!b)return p;if(/^[\w#.][\w\]*^|=!]*$/.test(a)){var j=0;switch(a.charAt(0)){case "#":j=a.slice(1);(p=f.getElementById(j))&&p.id!==j&&(p=f.all[j]);p=p?[p]:[];break;case ".":var d=a.slice(1);if(g)p=(p=b.getElementsByClassName(d)).length?p:[];else{for(var d=" "+d+" ",e=b.getElementsByTagName("*"),
l=0,i;i=e[l++];)-1!=(" "+i.className+" ").indexOf(d)&&(p[j++]=i);p=j?p:[]}break;default:p=(p=b.getElementsByTagName(a)).length?p:[]}}else{l=~a.indexOf("!=");if(u&&!l)try{p=b.querySelectorAll(a.replace(/=([^\]]+)/,'="$1"'))}catch(m){e=!0}if(e||!u||l){i=a.split(/ *, */);for(var x=i.length-1,Y=!!x,z,O,r,C,D,t,E,B,s,y,v;e=i[x--];){O=(z=e.replace(/(\([^)]*)\+/,"$1%").replace(/(\[[^\]]+)~/,"$1&").replace(/(~|>|\+)/," $1 ").split(/ +/)).length;l=0;r=" ";for(e=[b];j=z[l++];)if(" "!==j&&">"!==j&&"~"!==j&&
"+"!==j&&e){j=j.match(/([^[:.#]+)?(?:#([^[:.#]+))?(?:\.([^[:.]+))?(?:\[([^!&^*|$[:=]+)([!$^*|&]?=)?([^:\]]+)?\])?(?:\:([^(]+)(?:\(([^)]+)\))?)?/);C=j[1]||"*";D=j[2];d=j[3]?" "+j[3]+" ":"";t=[];j=E=0;for(s=l==O;B=e[E++];)switch(r){case " ":B=B.getElementsByTagName(C);for(v=0;y=B[v++];)if((!D||y.id===D)&&(!d||-1!=(" "+y.className+" ").indexOf(d))&&!y.yeasss)s&&(y.yeasss=1),t[j++]=y}e=t}else r=j;if(Y){if(!e.concat){t=[];for(v=0;y=e[v];)t[v++]=y;e=t}p=e.concat(1==p.length?p[0]:p)}else p=e}for(j=p.length;j--;)p[j].yeasss=
p[j].nodeIndex=p[j].nodeIndexLast=null}}return k(p)},g=!!f.getElementsByClassName,u=!!f.querySelectorAll;i=n;var O=/opera/i.test(navigator.userAgent)&&!!a.opera,x=Object.prototype,C=x.hasOwnProperty,D=x.toString,z=Array.prototype.slice,E=Array.prototype.forEach,v=Array.prototype.indexOf,s=Array.prototype.map,I=String.prototype.trim,ga=encodeURIComponent,Y=a.setTimeout,B=a.setInterval,ia=a.clearTimeout,Ja=a.clearInterval,y=Date.now||function(){return+new Date},N=/\s+/,qa=/\{(\w*)\}/mg,ka=/([-\\()^$.?+*])/g,
t="SG"+y(),ja=1,fa=function(){return!1},Z=function(){return!0},x=function(){},l={isArr:Array.isArray||function(a){return"[object Array]"===D.call(a)},isFn:function(a){return"[object Function]"===D.call(a)},isObj:function(a){if(!a||"object"!==typeof a||l.isArr(a)||l.isFn(a)||a.nodeType||a.setTimeout||a.constructor&&!C.call(a,"constructor")&&!C.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var b in a);return b===c||C.call(a,b)},isWin:function(a){return!!a&&"object"===typeof a&&"setInterval"in
a},ext:function(){var a,b,p,j,e,g=arguments,d=g[0]||{},f=1,i=g.length,k=!1;"boolean"===typeof d&&(k=d,d=g[1]||{},f=2);for("object"!==typeof d&&!l.isFn(d)&&(d={});f<i;f++)if(null!=(a=g[f]))for(b in a)p=d[b],j=a[b],d!==j&&(k&&j&&(l.isObj(j)||(e=l.isArr(j)))?(e?(e=!1,p=p&&l.isArr(p)?p:[]):p=p&&l.isObj(p)?p:{},d[b]=ma(k,p,j)):j!==c&&(d[b]=j));return d},copy:function(a){return l.ext(!0,l.isArr(a)?[]:{},a)},trim:function(a){a=""+a;return I?I.call(a):a.replace(/^\s+|\s+$/,"")},arrEach:function(a,b,c){if(E)E.call(a,
b,c);else for(var j=0,d=a.length;j<d;j++)b.call(c,a[j],j)},objEach:function(a,b,c){for(var j in a)C.call(a,j)&&b.call(c,a[j],j)},each:function(a,b,c){l["number"===typeof a.length?"arrEach":"objEach"](a,b,c)},map:function(a,b,c){if(s)return s.call(a,b,c);for(var j=0,d=a.length,g=Array(d);j<d;j++)g[j]=b.call(c,a[j],j);return g},indexOf:function(a,b,c){if(v)return v.call(a,b,c);var c=c||0,j=-1,d=0,g=a.length;if(c<g)for(0>c&&(d=Math.max(g-Math.abs(c),0));d<g;d++)if(a[d]===b){j=d;break}return j},format:function(a,
b){return a&&b?(""+a).replace(qa,function(a,h){return C.call(b,h)?b[h]:""}):""},objFormat:function(a,b){var c={};l.objEach(a,function(a,h){c[h]="string"===typeof a?l.format(a,b):l.isObj(a)?l.objFormat(a,b):a});return c},walker:function(a,b,c){for(var j=2<arguments.length,d=b.split("."),g=0,e=d.length,f=a,i,k=null,u,m;g<e;g++)if(i=d[g],k=(f=k||f)[i],m=g==e-1,null==k||!m&&!l.isObj(k))if(j)m||(k=f[i]={});else{k=null;break}g==e&&j?(u=f[i],f[i]=c):c=k;return j?u:c},resc:function(a){return(""+a).replace(ka,
"\\$1")},from:function(a){return null==a?[]:l.isArr(a)?a:[a]},mkarr:function(a){var b,d;if(a&&(d=a.length)!==c)try{b=z.call(a)}catch(j){for(b=Array(d);d--;)b[d]=a[d]}return b||[]},prm:function(a){var b,c,d=[];for(b in a)C.call(a,b)&&d.push(l.map([b,l.isFn(c=a[b])?c():c],ga).join("="));return d.join("&")},aprm:function(a,b){if(!b)return a;var a=""+a,c=[a],d=a.charAt(a.length-1);c.push(!~a.indexOf("?")?"?":"?"!==d&&"&"!==d?"&":"");c.push("object"===typeof b?l.prm(b):b);return c.join("")},url:function(a){var b=
[];a.scheme&&b.push(a.scheme,":");a.authority&&b.push("//",a.authority);a.path&&b.push("/",!a.path.indexOf("/")?a.path.slice(1):a.path);a.query&&b.push(l.aprm("?",a.query));a.fragment&&(a=a.fragment,b.push("#","object"===typeof a?l.prm(a):a));return b.join("")},$:function(a,b){return i(a,b)[0]||null},$$:i,css:function(a,b,c){if(!a)return null;var d=null;if(2<arguments.length&&b)a.style[b]=c;else{var g=a.ownerDocument.defaultView.getComputedStyle(a,null);1==arguments.length?d=l.mkarr(g):b&&(d=g.getPropertyValue(b))}return d},
addCls:function(a,b){for(var c=l.trim(b).split(N),d=c.length,g=a.className;d--;)b=c[d],l.hasCls(a,b)||(g+=" "+b);a.className=l.trim(g)},rmCls:function(a,b){if(1<arguments.length){for(var c=l.trim(b).split(N),d=c.length,g=a.className;d--;)b=c[d],g=g.replace(RegExp("(?:^|\\s+)"+l.resc(b)+"(?:\\s+|$)","g")," ");a.className=l.trim(g)}else a.className=""},hasCls:function(a,b){b=l.trim(b);return!(!a||!a.nodeType||!b||!~(" "+a.className+" ").indexOf(" "+b+" "))},cres:function(a){var a=l.trim(a),c=b.createDocumentFragment().appendChild(b.createElement("div"));
c.innerHTML=a;return l.mkarr(c.childNodes)},cre:function(a){a=l.trim(a);return"<"===a.charAt(0)&&">"===a.charAt(a.length-1)?l.cres(a)[0]:b.createElement(a)},rme:function(a){a&&a.parentNode&&(m.rm(a),a.parentNode.removeChild(a))},empty:function(a){for(var b;a&&(b=a.firstChild);)l.rme(b)},attr:function(a,b,c){2<arguments.length&&a.setAttribute(b,c);return a.getAttribute(b)},hasFocus:function(a){return!!a&&a.ownerDocument.activeElement===a},contains:b.documentElement.contains?function(a,b){return a!==
b&&(a.contains?a.contains(b):!0)}:b.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:fa},La=l,$=function(a,b){var c,d="string"===typeof a,g=!1,e;d?(a=l.trim(a),g=(!a.indexOf("#")||!a.indexOf("."))&&0>a.indexOf(ra)+a.indexOf(V)):a&&(e=!!a.nodeType);if(g||e){if(e&&a[t]?c=S[a[t]]:e||(c=S[a]),!c&&(g=i(a)[0]))c=S[g[t]||(g[t]=ja++)]=$(g.innerHTML||""),d&&(S[a]=c)}else c=a,c=S[c]||(S[c]=Function("_o","_e","var _=[],print=function(){_.push.apply(p,arguments)};with(_o||{}){_.push('"+
c.replace(Ma," ").split(ra).join("\t").replace(Na,"$1\r").replace(Oa,function(a,b){b=l.trim(b);return!b?"":["');","try{_.push("+b+")}catch(e){_e.push(e)}","_.push('"].join("")}).split("\t").join("');").split(V).join("_.push('").split("\r").join("\\'")+"')}return _.join('')"));c||(c=b?function(){return""}:"");return b?c(b,sa):c},ra="<%",V="%>",Ma=/[\r\t\n]/g,Na=RegExp("((^|"+l.resc(V)+")[^\\t]*)'","g"),Oa=RegExp("\\t=(.*?)"+l.resc(V),"g"),sa=[],S={};$.errs=sa;$.cch=S;La.tmpl=$;var ma=l.ext,K=l.isFn,
xa=l.$,va="addEventListener",X="preventDefault",ha="stopPropagation",Pa="altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),ya=b[va]?function(a,b,c){a[va](b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:
x,ta=b[va]?function(a,b,c){a.removeEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:x,Ca=function(a,b,c){ya(a,b,function(){ta(a,b,arguments.callee);return c.apply(a,arguments)})},Ga=function(a){return"defaultPrevented"in a?a.defaultPrevented:"returnValue"in a?!a.returnValue:"getPreventDefault"in a?a.getPreventDefault():!1},m=l.Event={fired:null,c:{},custom:{},hlink:function(a,b){b[t]=a[t]=a[t]||ja++;return b},fix:function(a){if(a[t])return a;for(var d=a,a=new m.Event(a),
g=0,e;e=Pa[g++];)a[e]=d[e];a.target||(a.target=a.srcElement||b);3===a.target.nodeType&&(a.target=a.target.parentNode);!a.relatedTarget&&a.fromElement&&(a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement);null==a.pageX&&null!=a.clientX&&(g=a.target.ownerDocument||b,d=g.documentElement,g=g.body,a.pageX=a.clientX+(d&&d.scrollLeft||g&&g.scrollLeft||0)-(d&&d.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(d&&d.scrollTop||g&&g.scrollTop||0)-(d&&d.clientTop||g&&g.clientTop||0));if(null==
a.which&&(null!=a.charCode||null!=a.keyCode))a.which=null!=a.charCode?a.charCode:a.keyCode;!a.metaKey&&a.ctrlKey&&(a.metaKey=a.ctrlKey);!a.which&&a.button!==c&&(a.which=a.button&1?1:a.button&2?3:a.button&4?2:0);return a},handler:function(b,c){b=m.fix(b||a.event);b.currentTarget=this;var d=m.c[this[t]][b.type],g;(c=c&&l.isArr(c)?l.mkarr(c):null)&&c.unshift(b);for(var e=0,f=d.length;e<f&&!(g=d[e],g=c?g.apply(this,c):g.call(this,b),!1===g&&(b[X](),b[ha]()),b.isImmediatePropagationStopped());e++);},add:function(b,
c,d){b&&c&&K(d)&&(b.setInterval&&b!=a&&!b.frameElement&&(b=a),l.arrEach(c.split(N),function(a){d[t]||(d[t]=ja++);var c=b[t]=b[t]||ja++,c=m.c[c]=m.c[c]||{},c=c[a]=c[a]||[],g=c.handle=function(a,b){if(!a||a.type!==m.fired)return m.handler.call(g.elem,a,b)};g.elem=b;if(1==c.push(d)&&(b.nodeType||b.setInterval)){var e=m.custom&&m.custom[a]&&m.custom[a].setup;(!e||!1===e.call(b,g))&&ya(b,a,c.handle)}}))},one:function(a,b,c){m.add(a,b,m.hlink(c,function(){m.rm(this,b,arguments.callee);return c.apply(this,
arguments)}))},rm:function(b,c,d){if(b)if(c)b.setInterval&&b!=a&&!b.frameElement&&(b=a),l.arrEach(c.split(N),function(a){var c=b[t],g=c&&m.c[c],e=g&&g[a];if(c&&g&&e){if(K(d)&&d[t])for(var f=e.length;f--;){if(e[f][t]==d[t]){e.splice(f,1);break}}else e.length=0;if(!e.length){if(b.nodeType||b.setInterval)f=m.custom&&m.custom[a]&&m.custom[a].teardown,(!f||!1===f.call(b,e.handle))&&ta(b,a,e.handle);delete g[a];for(a in g)return;delete m.c[c]}}});else{var c=(c=b[t])&&m.c[c],g=[],e;if(c){for(e in c)C.call(c,
e)&&g.push(e);m.rm(b,g.join(" "))}}},fire:function(a,b,c){var d;if(a&&b){var c=l.from(c),g=b.type||b,e,f="on"+g,i=a[t];if(d=(i=i&&m.c[i])&&i[g],i=d)e=b[t]?b:"object"===typeof b?new m.Event(g,b):new m.Event(b),e.type=g,e.target=e.currentTarget=a,i.handle.call(a,e,c);if(!e||!e.isDefaultPrevented()){var k;try{if((a.nodeType||a.setInterval)&&f&&a[g])(k=a[f])&&(a[f]=null),m.fired=g,a[g]()}catch(u){}k&&(a[f]=k)}m.fired=null}}};m.Event=function(a,b){a&&a.type?(this.origEvt=a,this.type=a.type,this.isDefaultPrevented=
Ga(a)?Z:fa):this.type=a;b&&ma(this,b);this.timeStamp=y();this[t]=!0};var ea=m.Event.prototype;ea[X]=function(){this.isDefaultPrevented=Z;var a=this.origEvt;if(a)if(a[X])a[X]();else a.returnValue=!1};ea[ha]=function(){this.isPropagationStopped=Z;var a=this.origEvt;if(a){if(a[ha])a[ha]();a.cancelBubble=!0}};ea.stopImmediatePropagation=function(){this.isImmediatePropagationStopped=Z;this[ha]()};ea.isDefaultPrevented=fa;ea.isPropagationStopped=fa;ea.isImmediatePropagationStopped=fa;var la={mouseover:"mouseenter",
mouseout:"mouseleave"};l.objEach(la,function(a,b){m.custom[a]={setup:function(){m.add(this,b,d)},teardown:function(){m.rm(this,b,d)}}});var Qa="cb"+t,Ka=l.jsonp=function(c){function g(){try{delete a[f]}catch(b){}}function d(a){m=k=!0;i&&i.onload();n&&n(a)}var e,f,i,k,u,m,x=c.success,n=c.error;return{send:function(n){m=!1;e=b.head||xa("head,body")||b.documentElement;f=Qa+ja++;i=l.cre("script");c.scriptCharset&&(i.charset=c.scriptCharset);i.async=!0;i.onload=i.onreadystatechange=function(){if(k||!this.readyState||
"loaded"===this.readyState)i.onload=i.onreadystatechange=null,i&&i.parentNode&&e.removeChild(i),i=null,ia(u),m=!0,k&&(a[f]=g)};var z=ma({},c.data);z[c.callbackParam]=f;n=l.aprm(n,z);i.src=n;a[f]=function(a){m=!0;g();x&&x(a)};c.timeout&&(u=Y(function(){d("timeout")},c.timeout));e.insertBefore(i,e.firstChild);return this},abort:function(){m||d("user");return this}}},r=e.evt={};l.arrEach("open openEnd close closeEnd enable enableEnd disable disableEnd destroy destroyEnd blockRequest successRequest completeRequest stopRequest errorRequest startRequest sendRequest passFilter failFilter rejectData acceptData render renderEnd focus focusEnd select selectEnd valueChange flushCache flushCacheEnd setCache setCacheEnd getCache getCacheEnd".split(" "),
function(a){this[a]=a},r);e.instances={};e.opts={enabled:!0,field:"#q",cont:"#sg",switcher:"sg-open",delay:250,valMin:1,valMax:255,valFilter:/(?:\S)/,url:"//suggests.go.mail.ru/sg_mobi?q={query}",callbackParam:"callback",reqTimeout:5E3,reqMax:2,scriptCharset:"windows-1251",dataFilter:function(a){return a},dataGet:function(a){return a&&a.items?a.items:[]},cch:!0,cchLimit:128,max:5,min:0,autoSubmit:!0,hover:"sg-item-hover",item:'<div class="sg-item"><%= itemData.textMarked || itemData.text %></div>',
result:function(a){return a.text},select:function(){},keynavDelay:150,preview:!0,debug:!1};e.utils=l;a.SG=a.SG||e})(window,document);(function(){var a=new Image;window.dataURISupported=!1;a.onload=a.onerror=function(a){a||(a=window.event);window.dataURISupported="load"===a.type};a.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="})();
(function(){var a=mr.id("q"),b=a.form,c=mr.id("go-form__sugg"),d=mr.id("go-form__sugg__items"),e=mr.id("go-form__sugg__loading"),i=mr.id("go-suggests__suggest-tmpl"),f=0,d=new SG({enabled:!1,field:a,cont:c,list:d,switcher:"go-form__sugg_open",autoSubmit:!0,preview:!0,hover:"go-form__sugg__item_select",max:7,scriptCharset:"utf-8",url:{scheme:0==location.href.indexOf("https://")?"https":"http",authority:"suggests.go.mail.ru",path:"sg_u",query:{q:"{query}"}},reqTimeout:3E3,reqData:{},dataFilter:function(a){if(a&&
a.items){var b=a.items,c,d,e=a.sites&&a.sites.length||0,f=[];for(d=0;d<e;d++)c=a.sites[d],"site"===c.type&&f.push(c);for(d=b.length;d--;)c=b[d],"site"===c.type&&b.splice(d,1);f.length&&b.unshift.apply(b,f)}return a},item:i,result:function(a){return a.text},onRenderEnd:function(){if(window.__ie7||window.__ie6)c.style.display="none",c.style.display="block"},onStartRequest:function(){e.style.display="block"},onStopRequest:function(){e.style.display="none"}}),k;d.opts({select:function(a){var c=a.itemData,
d=a.value;if("site"===c.type)k=a;else{a={us:d.length};if(c.mus){a.usmus=1;a.rch="l";for(var e=b.getElementsByTagName("input"),i=0,n=e.length;i<n;i++)d=e[i],"rch"==d.name&&d.parentNode.removeChild(d)}c.spcAuto&&(a.ussp=c.spcAuto);var z=document.createDocumentFragment(),E=[],v;for(v in a)a.hasOwnProperty(v)&&(c=a[v],d=document.createElement("input"),d.type="hidden",d.name=v,d.value=c,E.push(d),z.appendChild(d));b.appendChild(z);setTimeout(function(){for(var a=0,b=E.length;a<b;a++){var c=E[a];c.parentNode.removeChild(c)}E=
z=null},10);f=1}},unselect:function(){k=null}});var n=[null,"615232","615227","615230"],i=mr.id("search__button__wrapper__field");Splash.DOMEvent.addListener(i,"mousedown",function(){f=2});b._action=b.action;Splash.DOMEvent.addListener(b,"submit",function(c){if(b._submited)return!0;if(/^\s*$/.test(a.value))return a.focus(),!1;1!=f&&2!=f&&(f=3);var d=b._action,e="clb"+n[f];if(k){var i=k.itemData,C=k.value,D=document.createElement("form");D.action=d;D.method="get";D.target="_blank";var i={q:i.link,
sg:C,ce:1,sgsig:i.sig},z;for(z in i)if(i.hasOwnProperty(z)){var C=i[z],E=document.createElement("input");E.type="hidden";E.name=z;E.value=C;D.appendChild(E)}document.body.appendChild(D);D.submit();setTimeout(function(){D.parentNode.removeChild(D)},15);c.preventDefault()}f=0;b.action=d;b._submited=!0;clearTimeout(void 0);setTimeout(function(){b._submited=!1;b.action=b._action},300);mr.counter(e);setTimeout(function(){b.submit()},100);c.preventDefault();return!1});if(window.__ie6||window.__ie7)d.on("closeEnd",
function(){c.style.display="none";c.style.display="block"});d.enable()})();
(function(){var a=mr.id("search__projects-list");mr.bind(a,"click",function(a){var a=a||window.event,c=a.target||a.srcElement;if("A"===c.tagName){var d=mr.id("q").value;if(d){var e=mr.data(c,"search-href");if(e){if(c=mr.data(c,"search-param")){var i=document.createElement("form");i.action=e;i.method="get";i.setAttribute("accept-charset","windows-1251");e=document.createElement("input");e.type="hidden";e.name=c;e.value=d;i.appendChild(e);document.body.appendChild(i);i.submit()}else location.href=e+
encodeURIComponent(d);mr.preventDefault(a)}}}})})();
(function(){var a=mr.id("Auth"),b=mr.id("js-mailbox-emails"),c=mr.id("js-unread"),d=mr.tag("*",c,"js-txt")[0],e=mr.id("js-readed"),i=mr.id("js-mailbox-user"),f=mr.id("js-mailbox-avatar"),k=mr.id("js-mailbox-writemail"),n=mr.id("js-mailbox-exit"),g=mr.id("mailbox__login"),u=mr.id("mailbox__login__domain"),O=mr.id("domain-widget"),x=mr.id("mailbox__password"),C=mr.id("mailbox__auth__remember__checkbox"),D=mr.id("js-mailbox-enter"),z={},E=new Splash.EventEmitter;mr.data(a,"loadsubmit-counter","d703061");
window.Splash.ajaxUpdates.push({data:"mailbox",cb:function(a){z&&a.hasAuth!==z.hasAuth&&E.emit("switch",{data:a,oldData:z});D.href=a.HasAuth?mr.data(D,"enter-href"):mr.data(D,"login-href");if(a.HasAuth)i.innerHTML=a.ActiveEmail,mr.isMultiAuth&&(mr.multiuser.innerHTML=a.ActiveEmail),a.ActiveEmail!==z.ActiveEmail&&(f.style.backgroundImage="url(//filin.mail.ru/pic?from=splash&email="+a.ActiveEmail+(mr.retina?"&width=90&height=90":"&width=45&height=45")+")"),f.name=a.TotalUnread?mr.data(f,"counter-unread"):
mr.data(f,"counter-readed"),b.name=a.TotalUnread?mr.data(b,"counter-unread"):mr.data(b,"counter-readed"),k.name=a.TotalUnread?mr.data(k,"counter-unread"):mr.data(k,"counter-readed"),n.name=a.TotalUnread?mr.data(n,"counter-unread"):mr.data(n,"counter-readed"),a.TotalUnread?(d.innerHTML=a.TotalUnread+" "+_plural(a.TotalUnread,Splash.data.mailbox.newL)+" "+_plural(a.TotalUnread,Splash.data.mailbox.letters),c.style.display="inline",e.style.display="none"):(e.style.display="inline",c.style.display="none"),
mr.removeClass(document.body,"status__user_hasNoAuth"),mr.addClass(document.body,"status__user_hasAuth");else{if(document.activeElement&&-1!==document.activeElement.className.indexOf("mailbox"))return;var B=null,v=null;a.User&&(B=a.User+"@"+a.UserDomain);g.value&&(v=1!=mr.mailboxAuthType?g.value+u.options[-1==u.selectedIndex?1:u.selectedIndex].text:g.value);B!=v&&(x.value="");g.value=1!=mr.mailboxAuthType?a.User||"":a.User?a.User+"@"+a.UserDomain:"";mailboxLoginPlaceholder.toggle();for(mailboxPasswordPlaceholder.toggle();u&&
u.firstChild;)u.removeChild(u.firstChild);if(a.Domains[0].Domain){mr.domains=[];for(var B=a.Domains.length,v=null,s=0;s<B;s++)v=a.Domains[s].Domain,mr.domains.push(v)}else mr.domains=a.Domains,mr.extDomains=a.ExtDomains;B=0;for(v=mr.domains.length;B<v;B++)if(s=mr.domains[B],u){var y=document.createElement("option");y.value=s;y.selected=a.UserDomain==s;y.innerHTML="@"+s;u.appendChild(y)}if(mr.externalDomainsEnabled){y=document.createElement("option");y.disabled=!0;y.innerHTML="-------------------------";
u.appendChild(y);B=0;for(v=mr.extDomains.length;B<v;B++)s=mr.extDomains[B],u&&(y=document.createElement("option"),y.value=s,y.selected=a.UserDomain==s,y.innerHTML="@"+s,u.appendChild(y))}else a.UserDomainExt&&(B=document.createElement("option"),B.value=a.UserDomainExt,B.selected=!0,B.innerHTML="@"+a.UserDomainExt,u.appendChild(B));O&&O.mrChange();B=__PH.cookie.s.getGlobal("a")||mr.cookie("loginS");C.checked="string"!==typeof B||"1"===B;C.mrChange();E.emit("reset",a);mr.removeClass(document.body,"status__user_hasAuth");
mr.addClass(document.body,"status__user_hasNoAuth")}!a.HasAuth&&!a.User?mr.addClass(document.body,"status__user_hasNoAuth_noCookie"):mr.removeClass(document.body,"status__user_hasNoAuth_noCookie");z=a}});var v=mr.id("password_warning"),s=new Splash.Hint("",v);s.on("show",function(){mr.counter("d721322")});E.on("switch",s.hide);E.on("reset",function(){x.value||(s.hide(),v.style.display="none")});new function(){this.input=x;this.allowedSymbols=/^[0-9a-zA-Z!@#$%^&*()\-<>'"_+=;:,./?\\|`~[\]{}]+$/i;this.wrongAlpha=
/[\u0430-\u044f\u0410-\u042f\u0454\u0457\u0491\u0456]/i;this.wrongSymbolsMsg="\u0412\u044b \u0432\u0432\u0435\u043b\u0438<br/>\u043d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b";this.wrongBadLangMsg="\u0421\u043c\u0435\u043d\u0438\u0442\u0435 \u0440\u0430\u0441\u043a\u043b\u0430\u0434\u043a\u0443";this.warningEvent=new Splash.DOMEvent(this.input,"keyup",mr.proxy(function(){this.input.value&&!this.allowedSymbols.test(this.input.value)?
(this.wrongAlpha.test(this.input.value)?s.setContent(this.wrongBadLangMsg):s.setContent(this.wrongSymbolsMsg),v.style.display="block",mr.counter("d755623")):(s.hide(),v.style.display="none")},this));this.warningEvent.attach()};var I=!1,ga=new Splash.DOMEvent(document,"keyup",function(a){27==a.which&&(ga.detach(),I=!1)});window.Splash.mailboxDoCount=function(){if(I)return!1;ga.attach();return I=!0}})();
(function(){var a=mr.id("js-my-messages");mr.id("js-my-messages-link");var b=mr.id("js-my-messages-icon"),c=mr.id("js-my-friendships"),d=mr.id("js-my-friendships-link"),e=mr.id("js-my-friendships-icon");window.Splash.ajaxUpdates.push({data:"my",cb:function(i){i.HasMy?(a.innerHTML=i.MyMessages_cnt?i.MyMessages_cnt+" "+_plural(i.MyMessages_cnt,Splash.data.my.messages[0]):Splash.data.my.messages[1],c.innerHTML=i.MyFriendships_cnt?i.MyFriendships_cnt+" "+_plural(i.MyFriendships_cnt,Splash.data.my.friendships[0])+
Splash.data.my.friendships[1]:Splash.data.my.friendships[2],d.href=d.href.split("?")[0]+"?from=splash&requests="+i.MyFriendships_cnt+"#notify=people",mr["0"==i.MyMessages_cnt?"removeClass":"addClass"](b,"icon_counter_my-messages_unread"),mr["0"==i.MyFriendships_cnt?"removeClass":"addClass"](e,"icon_counter_my-friendship_unread"),mr.removeClass(document.body,"status__user_hasNoMy"),mr.addClass(document.body,"status__user_hasMy")):(mr.removeClass(document.body,"status__user_hasMy"),mr.addClass(document.body,
"status__user_hasNoMy"))}})})();
mr.mraSuggest&&function(a){function b(a){if(!d){clearTimeout(e);mr.counter("d929045");var b=mr.id("mraSuggest"),c=mr.id("mraTitle"),n=mr.id("mraDescription"),g=a.items&&a.items.length;try{if("ok"===a.status&&0!=g){for(var u=0;u<g;u++){var O=a.items[u],x=document.createElement("a"),C="http://agent.mail.ru/friends?partnerid=ava",D=1==g?"\u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442":"\u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442";x.className=
"social_mra__suggest__avatars__image";x.href=C;x.style.backgroundImage="url(//avt.foto.mail.ru/"+O.photoBox+"/_avatar22)";x.title=O.nick;x.name="clb877223";b.appendChild(x)}n.innerHTML=D;n.href=C;n.name="clb877221";c.href=C;c.name="clb877221";b.style.visibility="visible";mr.counter("d876981")}else"ok"===a.status&&0==g?mr.counter("d876980"):mr.counter("d876974")}catch(z){window.logError&&logError(z,"createMraSuggests"),mr.counter("d929044")}n.style.visibility="visible";d=!0}}function c(){e=setTimeout(function(){b({status:"error"})},
750);mr.getScript("//mrimraker1.mail.ru/agent_suggest?json=1&callback=getMraFriends",!1,"utf-8")}var d=!1,e;a.getMraFriends=function(a){b(a)};"opera"in a?a.addEventListener("DOMContentLoaded",function(){c()},!1):c()}(window,document);
(function(){var a={},b=0,c=[],d,e;window.reloadSlots=function(i,f){return function(){var k="reloadSlots"+b++;window[k]=function(b){try{var c=b.length,e,g,f,i,k;for(d=0;d<c;d++){k=b[d];e=k.slot;i=mr.id("slot_"+e);g=k.banner;var n=k.html,s=k.slot||"",I="u"+s+(new Date).getTime()*parseInt(1E5*Math.random()),n=n.replace(/(<script[^>]*>)\s*(<\!--|\/\/\s*<!\[CDATA\[)/gi,"$1;").replace(/\/\/\s*(--\>|\]\]>)\s*(<\/script>)/gi,";$2");f=n="<script>window.qwe"+I+s+' = "";<\/script>'+n.replace(/\w+\.write(ln)?\(/ig,
"qwe"+I+s+"+=(").replace(/<noscript>/ig,"<\!--").replace(/<\/noscript>/ig,"--\>")+'<span id="'+I+s+'"></span><script>mr.id("'+I+s+'").innerHTML = "<i style=\'display:none;\'>&nbsp;</i>" + qwe'+I+s+";<\/script>";null!=i.getAttribute("data-exb")&&i.setAttribute("data-exb",g);i.innerHTML='<i style="display:none;">&nbsp;</i>'+f;setTimeout(function(b){return function(){try{var c=b.getElementsByTagName("script"),d=function(b){function e(){c[b+1]&&d(b+1)}var g=c[b],f=g.text||g.textContent||g.innerHTML||
"",i=document.getElementsByTagName("head")[0]||document.documentElement,k=document.createElement("script");k.type="text/javascript";if(g.src)a[g.src]?e():(k.setAttribute("src",g.src+"?rnd="+Math.random()),k.onload=function(){i.removeChild(k);a[g.src]=1;e()},i.insertBefore(k,i.firstChild));else{try{k.appendChild(document.createTextNode(f))}catch(n){k.text=f}i.insertBefore(k,i.firstChild);i.removeChild(k);e()}};c.length&&d(0)}catch(e){window.logError&&logError(e,"execInnerScripts")}}}(i),0)}}catch(ga){window.logError&&
logError(ga,"reloadSlots")}};setTimeout(function(){window[k]=function(){}},6E4);var n=[];if(f)for(var g in f)f.hasOwnProperty(g)&&n.push([g,f[g]].join("="));d=0;for(e=i.length;d<e;d++)(g=mr.id("slot_"+i[d]).getAttribute("data-exb"))&&c.push(g);g="//ad.mail.ru/adq/?callback="+k+"&q="+i.join("&q=");_EXPERIMENTID&&(g+="&test_id="+_EXPERIMENTID);_PREVIEW&&(g+="&preview="+_PREVIEW);n.length&&(g+="&"+n.join("&"));c.length&&(g+="&exb="+c.join(";"),c.length=0);mr.getScript(g,!1,"utf-8")}}})();
(function(){function a(a,e){d=e;var g=c+(window.__PH&&a.data&&a.data.email?"&Login="+encodeURIComponent(a.data.email):"")+"&rnd="+(new Date).getTime()+Math.random();percent(mr.LF1Percent)&&((new Image).src=mr.getLf1Url({zero:1},g));mr.getJson(g,{},b);return!1}function b(a){try{if(a)for(var b=0,c=window.Splash.ajaxUpdates.length;b<c;b++){var e=window.Splash.ajaxUpdates[b];e.cb(e.data?a[e.data]:a)}}catch(f){window.logError&&logError(f,"getSplash")}"function"===typeof d&&d()}var c=location.href.split("#")[0].split("?")[0]+
"?json=1",d=function(){};if(__mailUpdated)__mailUpdated=!0,__PH.on("update",function(b,c){a(b,c)});else __PH.once("update",function(b,c){__mailUpdated=!0;__PH.on("update",function(b,c){a(b,c)});c()});__PH.on("authChange",function(b,c){a(b,c);e()});var e=reloadSlots([4015,217,4499]);if(mr.onFocusBannerReload){var i=!1;__PH.on("visibilitychange",function(a){a.data.visible&&i&&(f(),e(),mr.counter("d1464827"))});var f=function(){i=!1;setTimeout(function(){i=!0},6E5)};f()}})();
(function(){mr.cookie("newsT",null);window.newsTabs=new Splash.News(mr.id("news"),{tabs:{containerClass:"news__tabs",tabClass:"news__tabs__item",tabActiveClass:"news__tabs__item_selected",doubleTabClass:"news__tabs__item_double",tabLinkClass:"news__tabs__item__link",moreId:"news__more",moreIconId:"news__more__icon",moreDropdownId:"news__more__dropdown",moreOpenedClass:"news__tabs__more_opened",moreSelectedClass:"news__tabs__more_selected",moreDropdownItemClass:"news__tabs__more__dropdown__item",moreDropdownItemSelectedClass:"news__tabs__more__dropdown__item_selected",
moreDropdownItemLinkClass:"news__tabs__more__dropdown__item__link"},content:{containerId:"news__wrap",tabClass:"news__list",slotClass:"news__list__slot"},mask:{maskId:"news__mask"}});window.newsTabs.on("loaded",function(){var a;window.newsTabs.on("tab:activate",function(){clearTimeout(a);a=setTimeout(function(){mr.updateTGB&&(mr.counter("d1653700"),b())},100)});setTimeout(function(){mr.updateTGB=!1},2592E5);var b=reloadSlots([5349],{bv:mr.blockVersions.textBannerVersion})})})();
function splashMultiAuthInit(){mr.isMultiAuth="isMultiAuth"in __PH&&!0===__PH.isMultiAuth();if(mr.isMultiAuth){mr.multiuser=mr.id("MA_user-email");var a=Splash,b=function(b){mr.hasClass(f,k)&&(clearTimeout(n),mr.removeClass(f,k),f.style.width="",a.DOMEvent.removeListener(document,"click",c),b&&b.preventDefault())},c=function(a){var c;mr.hasParent(a.target,f)?(c=mr.hasParent(a.target,"js-logout")||mr.hasClass(a.target,"js-logout")&&(c=a.target))?(__PH.logoutAccount(mr.hasParent(c,"js-list-user").getAttribute("data-email"),
d),mr.counter("clb1199007"),a.preventDefault()):(c=mr.hasParent(a.target,"js-list-user")||mr.hasClass(a.target,"js-list-user")&&(c=a.target))?(__PH.switchAccount(c.getAttribute("data-email")),mr.counter("clb1195611"),a.preventDefault(),b()):mr.hasParent(a.target,"js-button")||mr.hasClass(a.target,"js-button")&&a.target?(a.preventDefault(),b()):mr.hasParent(a.target,"js-login")||mr.hasClass(a.target,"js-login")&&a.target?(mr.counter("clb1195612"),b(),mr.isPHAuthForm&&(a.preventDefault(),__PH.authForm.show())):
mr.isNode(a.target)&&"a"===a.target.tagName.toLowerCase()&&b():b()},d=function(a){var b=mr.id("multiAuthMenuList");if("error"!==a.status){a=a.accounts;1<a.length?(mr.addClass(f,"multiauth__menu_multi"),10<a.length?mr.addClass(f,"multiauth__menu_limit"):mr.removeClass(f,"multiauth__menu_limit")):(mr.removeClass(f,"multiauth__menu_multi"),mr.removeClass(f,"multiauth__menu_limit"));for(var c=[],d=0,e=a.length;d<e;d++){var i="",k=a[d];0===d?i=" multiauth__menu__dropdown__list__item_first":d===a.length&&
(i=" multiauth__menu__dropdown__list__item_last");k.active&&(i+=" multiauth__menu__dropdown__list__item_current");var n=k.counters&&k.counters.mail;c.push("<div"+(!k.active?' tabindex="0"':"")+' class="multiauth__menu__dropdown__list__item'+(!k.active?" js-list-user":"")+i+'" data-email="'+k.email+'" onkeypress="if ((event.which || event.charCode || event.keyCode) === 13){var t = (event.target || event.srcElement); t.nodeType == 3 && (t = t.parentNode); t.click();}"><div class="multiauth__menu__dropdown__list__item__avatar" style="background-image:url(//filin.mail.ru/pic?from=splash&email='+
k.email+'&width=45&height=45);"></div><div class="multiauth__menu__dropdown__list__item__info"><div class="multiauth__menu__dropdown__list__item__info__email">'+(!k.active?'<div class="multiauth__menu__dropdown__list__item__info__email__counter'+(n?" multiauth__menu__dropdown__list__item__info__email__counter_visible":"")+'"><i class="multiauth__menu__dropdown__list__item__info__email__counter__icon"></i><span class="multiauth__menu__dropdown__list__item__info__email__counter__text">'+n+"</span></div>":
"")+'<div class="multiauth__menu__dropdown__list__item__info__email__text">'+k.email+'</div></div><div class="multiauth__menu__dropdown__list__item__info__text">'+(k.firstName&&k.lastName?k.firstName+" "+k.lastName:"")+'</div></div><div class="multiauth__menu__dropdown__list__item__logout js-logout"><span class="portal-button portal-button_only-icon"><span class="portal-button__fake"><span class="portal-button__fake__icon portal-button__fake__icon_multiauth portal-button__fake__icon_multiauth_exit"></span></span></span></div></div>')}b.innerHTML=
c.join("")}},e=mr.id("js-mailbox-user"),i=mr.id("js-mailbox-user-wrap"),f=mr.id("multiAuthMenu"),k="multiauth__menu_open";mr.id("multiAuthHolder").appendChild(f);mr.addClass(i,"w-mailbox__userinfo__email_multiauth");a.DOMEvent.on(e,"click",function(e){if(mr.hasClass(f,k))b(e);else if(!mr.hasClass(f,k)){var i=function(){n&&(mr.addClass(f,k),a.DOMEvent.on(document,"click",c),n=!1)},n=!0,x;mr.addClass(f,"multiauth__menu__dropdown_loading");mr.removeClass(f,"multiauth__menu__dropdown_error");x=setTimeout(i,
100);__PH.loadAccountsList(function(a){clearTimeout(x);"timeout"===a.status||"error"===a.status?(mr.removeClass(f,"multiauth__menu__dropdown_loading"),mr.addClass(f,"multiauth__menu__dropdown_error")):(d(a),mr.removeClass(f,"multiauth__menu__dropdown_loading"));i();f.style.width=f.offsetWidth+"px"});mr.counter("clb1195610");e&&e.preventDefault()}});a.DOMEvent.on(f,"mouseover",function(){clearTimeout(n)});a.DOMEvent.on(f,"mouseout",function(){clearTimeout(n);n=setTimeout(b,4E3)});var n}}
splashRadar("JSInit",1);splashRadar._JSINITTime=(new Date).getTime()-splashRadar._JSINITTime;
